---
resources:
 - name: resource-git
   type: git 
   source:
     uri: https://github.com/bipin1086/gitpipeline.git
     branch: main

jobs:
  - name: pass-input-output
    public: true
    plan:
      - get: resource-git
      - task: create_files
        file: resource-git/create_file.yml
      - task: show_files
        file: resource-git/show_files.yml
